
/******************************************************************************
 * FILE: main.c
 * PROJECT: Self-Healing FPGA - STM32F401CCU6 (Black Pill) Firmware
 * 
 * WHAT THIS FILE DOES:
 *   1. Reads IMU6050 sensor via I2C1 (PB6=SCL, PB7=SDA)
 *   2. Runs complementary filter to get roll & pitch
 *   3. Sends filtered angles to FPGA via SPI1 (PA4=CS, PA5=SCK, PA6=MISO, PA7=MOSI)
 *   4. Reads fault status back from FPGA via SPI
 *   5. Logs everything to PC via USART2 (PA2=TX, PA3=RX) through CP2102
 *
 * TOOL: STM32CubeIDE
 * BOARD: WeAct Black Pill (STM32F401CCU6)
 *
 * HOW TO SET UP IN STM32CubeIDE (CubeMX):
 *   - System Clock: HSE 25MHz -> PLL -> 84 MHz SYSCLK
 *   - I2C1: PB6 (SCL), PB7 (SDA), 100 kHz standard mode
 *   - SPI1: PA5 (SCK), PA6 (MISO), PA7 (MOSI), software NSS
 *           Mode: Full-Duplex Master, 8-bit, CPOL=0, CPHA=0, Prescaler=64 (~1.3 MHz)
 *   - PA4: GPIO Output (SPI chip select, directly controlled)
 *   - USART2: PA2 (TX), PA3 (RX), 115200 baud, 8N1
 *   - Generate code, then paste sections below into generated main.c
 ******************************************************************************/

/* ========================== INCLUDES ====================================== */
#include "main.h"
#include <stdio.h>
#include <string.h>
#include <math.h>

/* ========================== PERIPHERAL HANDLES ============================ */
/* These are auto-generated by CubeMX. You will see them in main.c already. */
I2C_HandleTypeDef hi2c1;       // I2C1 handle (for IMU6050)
SPI_HandleTypeDef hspi1;       // SPI1 handle (for FPGA)
UART_HandleTypeDef huart2;     // USART2 handle (for PC logging)

/* ========================== IMU6050 DEFINES =============================== */
/*
 * MPU6050 I2C address: 0x68 (7-bit). HAL expects 8-bit address, so shift left:
 *   0x68 << 1 = 0xD0
 *
 * Key registers:
 *   PWR_MGMT_1 (0x6B): Power management. Write 0x00 to wake up.
 *   ACCEL_CONFIG (0x1C): Accelerometer range. 0x00 = +/-2g.
 *   GYRO_CONFIG (0x1B): Gyroscope range. 0x08 = +/-500 deg/s.
 *   ACCEL_XOUT_H (0x3B): Start of 14-byte burst read (accel + temp + gyro).
 */
#define IMU_ADDR        0xD0    // 0x68 << 1
#define WHO_AM_I_REG    0x75
#define PWR_MGMT_1      0x6B
#define ACCEL_CONFIG     0x1C
#define GYRO_CONFIG      0x1B
#define ACCEL_XOUT_H    0x3B

/* ========================== FILTER PARAMETERS ============================= */
/*
 * Complementary filter:
 *   angle = ALPHA * (angle + gyro_rate * dt) + (1 - ALPHA) * accel_angle
 *
 * ALPHA = 0.98 means we trust gyro 98% and accel 2%.
 * dt = 0.01 seconds (100 Hz loop).
 *
 * Gyro sensitivity at +/-500 deg/s range = 65.5 LSB/(deg/s)
 * Accel sensitivity at +/-2g range = 16384 LSB/g
 */
#define ALPHA           0.98f
#define DT              0.01f   // 10 ms loop period
#define GYRO_SENS       65.5f   // LSB per deg/s at +/-500 range
#define ACCEL_SENS      16384.0f // LSB per g at +/-2g range
#define RAD_TO_DEG      57.2957795f

/* ========================== GLOBAL VARIABLES ============================== */

// Raw sensor data (16-bit signed, from MPU6050)
int16_t accel_raw[3];   // ax, ay, az in LSB
int16_t gyro_raw[3];    // gx, gy, gz in LSB

// Physical values after conversion
float ax_g, ay_g, az_g;         // acceleration in g
float gx_dps, gy_dps, gz_dps;   // angular rate in deg/s

// Gyro calibration offsets (measured at startup)
float gyro_offset_x = 0.0f;
float gyro_offset_y = 0.0f;
float gyro_offset_z = 0.0f;

// Filtered angles (output of complementary filter)
float roll_deg  = 0.0f;
float pitch_deg = 0.0f;

// SPI packet buffer
uint8_t spi_tx_buf[10];   // data sent to FPGA
uint8_t spi_rx_buf[10];   // data received from FPGA

// UART print buffer
char uart_buf[128];

/* ========================== FUNCTION PROTOTYPES =========================== */
void IMU_Init(void);
void IMU_Calibrate_Gyro(void);
void IMU_Read_All(void);
void Complementary_Filter_Update(void);
void Send_To_FPGA(void);
void Log_To_PC(void);

/* ========================== REDIRECT printf TO UART ======================= */
/*
 * This lets you use printf() and it automatically sends text over USART2.
 * Add this function, and in Project Settings enable "Use float with printf".
 */
int _write(int file, char *ptr, int len) {
    HAL_UART_Transmit(&huart2, (uint8_t*)ptr, len, 100);
    return len;
}

/* ========================== MAIN FUNCTION ================================= */
int main(void)
{
    /* ---- CubeMX auto-generated init (do not modify) ---- */
    HAL_Init();
    SystemClock_Config();     // Configures 84 MHz from HSE
    MX_GPIO_Init();           // Configures PA4 as output (SPI CS)
    MX_I2C1_Init();           // Configures I2C1 on PB6/PB7
    MX_SPI1_Init();           // Configures SPI1 on PA5/PA6/PA7
    MX_USART2_UART_Init();    // Configures USART2 on PA2/PA3

    /* ---- Set SPI CS high (deselect FPGA) ---- */
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_SET);

    /* ---- Initialize IMU6050 ---- */
    printf("System starting...\r\n");
    IMU_Init();

    /* ---- Calibrate gyro (keep sensor still for ~2 seconds) ---- */
    printf("Calibrating gyro... keep sensor still!\r\n");
    IMU_Calibrate_Gyro();
    printf("Calibration done. Offsets: gx=%.2f gy=%.2f gz=%.2f\r\n",
           gyro_offset_x, gyro_offset_y, gyro_offset_z);

    /* ========================== MAIN LOOP ================================= */
    /*
     * Runs at ~100 Hz (every 10 ms):
     *   1. Read IMU
     *   2. Run complementary filter
     *   3. Send angles to FPGA via SPI
     *   4. Log to PC via UART
     */
    while (1)
    {
        // Step 1: Read accelerometer and gyroscope
        IMU_Read_All();

        // Step 2: Run complementary filter -> updates roll_deg, pitch_deg
        Complementary_Filter_Update();

        // Step 3: Pack and send to FPGA via SPI
        Send_To_FPGA();

        // Step 4: Log to PC
        Log_To_PC();

        // Step 5: Wait 10 ms (gives ~100 Hz loop)
        HAL_Delay(10);
    }
}

/*******************************************************************************
 * SECTION A: IMU6050 INITIALIZATION
 *
 * Steps:
 *   1. Check WHO_AM_I register (should return 0x68).
 *   2. Wake up sensor (write 0x00 to PWR_MGMT_1).
 *   3. Set accelerometer range to +/-2g.
 *   4. Set gyroscope range to +/-500 deg/s.
 ******************************************************************************/
void IMU_Init(void)
{
    uint8_t check = 0;
    uint8_t data;

    // 1. Verify sensor is connected
    HAL_I2C_Mem_Read(&hi2c1, IMU_ADDR, WHO_AM_I_REG, 1, &check, 1, 1000);
    if (check == 0x68) {
        printf("IMU6050 found! (WHO_AM_I = 0x%02X)\r\n", check);
    } else {
        printf("ERROR: IMU6050 not found (got 0x%02X)\r\n", check);
        // Halt here if sensor not found
        while(1) { HAL_Delay(1000); }
    }

    // 2. Wake up (exit sleep mode)
    data = 0x00;
    HAL_I2C_Mem_Write(&hi2c1, IMU_ADDR, PWR_MGMT_1, 1, &data, 1, 1000);
    HAL_Delay(50);

    // 3. Set accel range to +/-2g (register value 0x00)
    data = 0x00;
    HAL_I2C_Mem_Write(&hi2c1, IMU_ADDR, ACCEL_CONFIG, 1, &data, 1, 1000);

    // 4. Set gyro range to +/-500 deg/s (register value 0x08)
    data = 0x08;
    HAL_I2C_Mem_Write(&hi2c1, IMU_ADDR, GYRO_CONFIG, 1, &data, 1, 1000);

    HAL_Delay(100);
}

/*******************************************************************************
 * SECTION B: GYRO CALIBRATION
 *
 * Reads 200 gyro samples while sensor is stationary.
 * Averages them to find the "zero offset" for each axis.
 * This offset is subtracted during normal operation to remove drift.
 ******************************************************************************/
void IMU_Calibrate_Gyro(void)
{
    uint8_t buf[6];
    float sum_x = 0, sum_y = 0, sum_z = 0;
    int16_t gx, gy, gz;

    for (int i = 0; i < 200; i++)
    {
        // Read 6 bytes starting at GYRO_XOUT_H (0x43)
        HAL_I2C_Mem_Read(&hi2c1, IMU_ADDR, 0x43, 1, buf, 6, 1000);

        gx = (int16_t)(buf[0] << 8 | buf[1]);
        gy = (int16_t)(buf[2] << 8 | buf[3]);
        gz = (int16_t)(buf[4] << 8 | buf[5]);

        sum_x += (float)gx;
        sum_y += (float)gy;
        sum_z += (float)gz;

        HAL_Delay(10);
    }

    // Average = total offset in raw LSB units
    gyro_offset_x = sum_x / 200.0f;
    gyro_offset_y = sum_y / 200.0f;
    gyro_offset_z = sum_z / 200.0f;
}

/*******************************************************************************
 * SECTION C: READ ALL SENSOR DATA
 *
 * Burst-reads 14 bytes starting at ACCEL_XOUT_H (0x3B):
 *   Bytes 0-1: Accel X (high byte first)
 *   Bytes 2-3: Accel Y
 *   Bytes 4-5: Accel Z
 *   Bytes 6-7: Temperature (we ignore this)
 *   Bytes 8-9: Gyro X
 *   Bytes 10-11: Gyro Y
 *   Bytes 12-13: Gyro Z
 *
 * Then converts raw values to physical units.
 ******************************************************************************/
void IMU_Read_All(void)
{
    uint8_t buf[14];

    // Burst read 14 bytes
    HAL_I2C_Mem_Read(&hi2c1, IMU_ADDR, ACCEL_XOUT_H, 1, buf, 14, 1000);

    // Combine high and low bytes into 16-bit signed integers
    accel_raw[0] = (int16_t)(buf[0]  << 8 | buf[1]);   // Accel X
    accel_raw[1] = (int16_t)(buf[2]  << 8 | buf[3]);   // Accel Y
    accel_raw[2] = (int16_t)(buf[4]  << 8 | buf[5]);   // Accel Z
    // buf[6..7] = temperature, skip
    gyro_raw[0]  = (int16_t)(buf[8]  << 8 | buf[9]);   // Gyro X
    gyro_raw[1]  = (int16_t)(buf[10] << 8 | buf[11]);  // Gyro Y
    gyro_raw[2]  = (int16_t)(buf[12] << 8 | buf[13]);  // Gyro Z

    // Convert accelerometer to g
    ax_g = (float)accel_raw[0] / ACCEL_SENS;
    ay_g = (float)accel_raw[1] / ACCEL_SENS;
    az_g = (float)accel_raw[2] / ACCEL_SENS;

    // Convert gyroscope to deg/s, subtract calibration offset
    gx_dps = ((float)gyro_raw[0] - gyro_offset_x) / GYRO_SENS;
    gy_dps = ((float)gyro_raw[1] - gyro_offset_y) / GYRO_SENS;
    gz_dps = ((float)gyro_raw[2] - gyro_offset_z) / GYRO_SENS;
}

/*******************************************************************************
 * SECTION D: COMPLEMENTARY FILTER
 *
 * THE CORE ALGORITHM:
 *
 *   1. PREDICTION (from gyroscope):
 *      roll_gyro  = roll  + gx_dps * dt
 *      pitch_gyro = pitch + gy_dps * dt
 *
 *   2. MEASUREMENT (from accelerometer):
 *      roll_acc  = atan2(ay, az) * RAD_TO_DEG
 *      pitch_acc = atan2(-ax, sqrt(ay^2 + az^2)) * RAD_TO_DEG
 *
 *   3. FUSION:
 *      roll  = ALPHA * roll_gyro  + (1 - ALPHA) * roll_acc
 *      pitch = ALPHA * pitch_gyro + (1 - ALPHA) * pitch_acc
 *
 * WHY:
 *   - Gyro is accurate short-term but drifts over time.
 *   - Accel is noisy but doesn't drift.
 *   - Complementary filter combines both: trust gyro 98%, correct with accel 2%.
 ******************************************************************************/
void Complementary_Filter_Update(void)
{
    // Step 1: Predict angles using gyroscope integration
    float roll_gyro  = roll_deg  + gx_dps * DT;
    float pitch_gyro = pitch_deg + gy_dps * DT;

    // Step 2: Compute angles from accelerometer (absolute reference)
    float roll_acc  = atan2f(ay_g, az_g) * RAD_TO_DEG;
    float pitch_acc = atan2f(-ax_g, sqrtf(ay_g * ay_g + az_g * az_g)) * RAD_TO_DEG;

    // Step 3: Fuse with complementary filter
    roll_deg  = ALPHA * roll_gyro  + (1.0f - ALPHA) * roll_acc;
    pitch_deg = ALPHA * pitch_gyro + (1.0f - ALPHA) * pitch_acc;
}

/*******************************************************************************
 * SECTION E: SEND DATA TO FPGA VIA SPI
 *
 * Packet format (9 bytes):
 *   Byte 0:    Header = 0xAA
 *   Byte 1-2:  Roll in centi-degrees (int16_t). E.g. 12.34 deg -> 1234
 *   Byte 3-4:  Pitch in centi-degrees (int16_t)
 *   Byte 5-6:  Simple checksum (sum of bytes 0..4, 16-bit)
 *   Byte 7:    Footer = 0x55
 *
 * SPI settings: CPOL=0, CPHA=0 (Mode 0), 8-bit, MSB first.
 * STM32 is master, FPGA is slave.
 *
 * Pin connections:
 *   STM32 PA5 (SCK)  -> FPGA pin for SCK
 *   STM32 PA7 (MOSI) -> FPGA pin for MOSI
 *   STM32 PA6 (MISO) <- FPGA pin for MISO
 *   STM32 PA4 (CS)   -> FPGA pin for CS (directly driven as GPIO)
 ******************************************************************************/
void Send_To_FPGA(void)
{
    // Convert float angles to centi-degrees (integer * 100)
    int16_t roll_cd  = (int16_t)(roll_deg  * 100.0f);
    int16_t pitch_cd = (int16_t)(pitch_deg * 100.0f);

    // Build packet
    spi_tx_buf[0] = 0xAA;                          // Header
    spi_tx_buf[1] = (uint8_t)(roll_cd >> 8);        // Roll high byte
    spi_tx_buf[2] = (uint8_t)(roll_cd & 0xFF);      // Roll low byte
    spi_tx_buf[3] = (uint8_t)(pitch_cd >> 8);       // Pitch high byte
    spi_tx_buf[4] = (uint8_t)(pitch_cd & 0xFF);     // Pitch low byte

    // Simple checksum: sum of bytes 0..4
    uint16_t chk = 0;
    for (int i = 0; i < 5; i++) chk += spi_tx_buf[i];
    spi_tx_buf[5] = (uint8_t)(chk >> 8);            // Checksum high
    spi_tx_buf[6] = (uint8_t)(chk & 0xFF);          // Checksum low
    spi_tx_buf[7] = 0x55;                           // Footer

    // Pull CS low -> transmit -> pull CS high
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_RESET);  // CS = LOW
    HAL_SPI_TransmitReceive(&hspi1, spi_tx_buf, spi_rx_buf, 8, 100);
    HAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_SET);    // CS = HIGH

    /*
     * spi_rx_buf now contains whatever the FPGA sent back during
     * the same 8 clock bytes. We can check:
     *   spi_rx_buf[0] = FPGA status byte (e.g. fault flag, state)
     */
}

/*******************************************************************************
 * SECTION F: LOG TO PC VIA UART
 *
 * Sends roll, pitch, and FPGA fault status over USART2 at 115200 baud.
 * CP2102 USB-UART converter connects:
 *   STM32 PA2 (TX) -> CP2102 RX
 *   STM32 PA3 (RX) <- CP2102 TX
 *   Common GND
 *
 * Open a serial terminal (PuTTY, TeraTerm, etc.) at 115200 baud to see output.
 ******************************************************************************/
void Log_To_PC(void)
{
    uint8_t fpga_status = spi_rx_buf[0];

    printf("R:%.2f P:%.2f FPGA:0x%02X\r\n", roll_deg, pitch_deg, fpga_status);
}

/*
 * NOTE: The following functions are auto-generated by CubeMX.
 * You do NOT need to write them manually.
 * They are listed here so you know what CubeMX creates for you.
 *
 *   void SystemClock_Config(void);
 *   static void MX_GPIO_Init(void);
 *   static void MX_I2C1_Init(void);
 *   static void MX_SPI1_Init(void);
 *   static void MX_USART2_UART_Init(void);
 */
